Repository litentry/litentry-pallets, pull requests merged in 2021-08, with the labels that each got.

#30 add benchmark for on_initialize
  pallets/offchain-worker/src/benchmarking.rs
  pallets/offchain-worker/src/lib.rs
  pallets/offchain-worker/src/tests.rs
  pallets/offchain-worker/src/weights.rs
Labels: F2-tests/benchmarks/ci

#76 V2 template solution for event and improvement for run_to_block
  pallets/nft/src/impl_nonfungibles.rs
  pallets/nft/src/lib.rs
  pallets/nft/src/mock.rs
  pallets/nft/src/tests.rs
Labels: S1-pleasereview

#77 Nft test pre
  pallets/nft/src/impl_nonfungibles.rs
  pallets/nft/src/lib.rs
  pallets/nft/src/mock.rs
  pallets/nft/src/tests.rs
Labels: S1-pleasereview

#84 Nft test pre
  pallets/nft/src/lib.rs
  pallets/nft/src/tests.rs
Labels: S1-pleasereview

#85 - merge burn flag with burn event
  pallets/nft/src/lib.rs
  pallets/nft/src/tests.rs
Labels: S1-pleasereview

#82 Prune README.md
  README.md
Labels: F3-documentation, S1-pleasereview
